// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
/// 
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-T0oPl65AjT4rWrtU3HKzl06ObhSoR0k',
    appId: '1:416094349285:web:b280d925b64b15836b310c',
    messagingSenderId: '416094349285',
    projectId: 'chat-app-1b888',
    authDomain: 'chat-app-1b888.firebaseapp.com',
    storageBucket: 'chat-app-1b888.appspot.com',
    measurementId: 'G-ERZ6FKR49H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYI3qDqhA7WE2493y_ysfBmA9jtNxetuk',
    appId: '1:416094349285:android:a639d4aaccecb7566b310c',
    messagingSenderId: '416094349285',
    projectId: 'chat-app-1b888',
    storageBucket: 'chat-app-1b888.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzKBgJcehvVC0gznKyEdY2_uJ69Ij_iKg',
    appId: '1:416094349285:ios:90f5c708c9a9ec556b310c',
    messagingSenderId: '416094349285',
    projectId: 'chat-app-1b888',
    storageBucket: 'chat-app-1b888.appspot.com',
    iosBundleId: 'com.example.chatsapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzKBgJcehvVC0gznKyEdY2_uJ69Ij_iKg',
    appId: '1:416094349285:ios:90f5c708c9a9ec556b310c',
    messagingSenderId: '416094349285',
    projectId: 'chat-app-1b888',
    storageBucket: 'chat-app-1b888.appspot.com',
    iosBundleId: 'com.example.chatsapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-T0oPl65AjT4rWrtU3HKzl06ObhSoR0k',
    appId: '1:416094349285:web:9b3d6b04a300b4cf6b310c',
    messagingSenderId: '416094349285',
    projectId: 'chat-app-1b888',
    authDomain: 'chat-app-1b888.firebaseapp.com',
    storageBucket: 'chat-app-1b888.appspot.com',
    measurementId: 'G-H02WGX8NLJ',
  );
}
